/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arduino;

import arduino.conexiones.baseDatosObjeto;
import java.time.LocalDate;
import static java.time.LocalDate.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import panamahitek.Arduino.PanamaHitek_Arduino;
import static sun.security.krb5.internal.KerberosTime.now;
import arduino.conexiones.baseDatosObjeto;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JTextField;
import java.sql.Connection;

/**
 *
 * @author USUARIO
 */
public class visual extends javax.swing.JFrame {

    Calendar fecha_actual = new GregorianCalendar();

    Thread h1;
    /**
     * Creates new form visual
     */
    // arduino coneccion
    PanamaHitek_Arduino Arduino = new PanamaHitek_Arduino();
    baseDatosObjeto metodo = new baseDatosObjeto();
    Connection con = metodo.conexion();

    public visual() {
        initComponents();
        fDataTime.setCalendar(fecha_actual);
        try {
            Arduino.arduinoTX("COM9", 9600);
        } catch (Exception ex) {
            Logger.getLogger(visual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // 
    public void ImagenPuertaCerrada() {
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduino/puetacerada.jpg")));
    }

    public void ImagenPuertaAbierta() {
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduino/puestaabierta.jpg")));
    }

    public void abiertaTrue() {

        String sql = "INSERT INTO estado_objeto (FECHA,ESTADO) VALUES(?,?)";
        PreparedStatement pst;
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, ((JTextField) fDataTime.getDateEditor().getUiComponent()).getText());
            pst.setBoolean(2, true);
            pst.execute();
            javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso \n", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro fallido \n", "Aviso", javax.swing.JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(visual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void cerradaFalce() {
        String sql = "INSERT INTO estado_objeto (FECHA,ESTADO) VALUES(?,?)";
        PreparedStatement pst;
        try {
            pst = con.prepareStatement(sql);
            pst.setString(1, ((JTextField) fDataTime.getDateEditor().getUiComponent()).getText());
            pst.setBoolean(2, false);
            pst.execute();
            javax.swing.JOptionPane.showMessageDialog(this, "Registro exitoso \n", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro fallido \n", "Aviso", javax.swing.JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(visual.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        fDataTime = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClose.setText("Close door");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnOpen.setText("Open door");
        btnOpen.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btnOpenComponentAdded(evt);
            }
        });
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        lblEstado.setText("....");

        lblImagen.setText(".");

        fDataTime.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        fDataTime.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fDataTime, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fDataTime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnOpenComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOpenComponentAdded

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
// TODO add your handling code here:

        lblEstado.setText("Puerta abierta");
        ImagenPuertaAbierta();
        try {
            Arduino.sendData("2");
            abiertaTrue();
        } catch (Exception ex) {
            abiertaTrue();

        }

    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        lblEstado.setText("Puerta cerrada");
        ImagenPuertaCerrada();
        try {
            Arduino.sendData("1");
            cerradaFalce();

        } catch (Exception ex) {
            cerradaFalce();

        }

    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new visual().setVisible(true);

            }

            private void calcula() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            private void While(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOpen;
    private com.toedter.calendar.JDateChooser fDataTime;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
